/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProfileListingsRouteImport } from './routes/profile/listings'
import { Route as ProductsListingIdIndexRouteImport } from './routes/products/$listingId/index'
import { Route as ProductsListingIdEditRouteImport } from './routes/products/$listingId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileListingsRoute = ProfileListingsRouteImport.update({
  id: '/profile/listings',
  path: '/profile/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListingIdIndexRoute = ProductsListingIdIndexRouteImport.update({
  id: '/products/$listingId/',
  path: '/products/$listingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListingIdEditRoute = ProductsListingIdEditRouteImport.update({
  id: '/products/$listingId/edit',
  path: '/products/$listingId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId/': typeof ProductsListingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/products': typeof ProductsIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId': typeof ProductsListingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId/': typeof ProductsListingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/products/'
    | '/products/$listingId/edit'
    | '/products/$listingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/products'
    | '/products/$listingId/edit'
    | '/products/$listingId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/products/'
    | '/products/$listingId/edit'
    | '/products/$listingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  ProfileListingsRoute: typeof ProfileListingsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsListingIdEditRoute: typeof ProductsListingIdEditRoute
  ProductsListingIdIndexRoute: typeof ProductsListingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/listings': {
      id: '/profile/listings'
      path: '/profile/listings'
      fullPath: '/profile/listings'
      preLoaderRoute: typeof ProfileListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$listingId/': {
      id: '/products/$listingId/'
      path: '/products/$listingId'
      fullPath: '/products/$listingId/'
      preLoaderRoute: typeof ProductsListingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$listingId/edit': {
      id: '/products/$listingId/edit'
      path: '/products/$listingId/edit'
      fullPath: '/products/$listingId/edit'
      preLoaderRoute: typeof ProductsListingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  ProfileListingsRoute: ProfileListingsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsListingIdEditRoute: ProductsListingIdEditRoute,
  ProductsListingIdIndexRoute: ProductsListingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
