/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as FavoritesIndexRouteImport } from './routes/favorites/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileListingsRouteImport } from './routes/profile/listings'
import { Route as ProductsListingIdIndexRouteImport } from './routes/products/$listingId/index'
import { Route as ProductsListingIdEditRouteImport } from './routes/products/$listingId/edit'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileListingsRoute = ProfileListingsRouteImport.update({
  id: '/profile/listings',
  path: '/profile/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListingIdIndexRoute = ProductsListingIdIndexRouteImport.update({
  id: '/products/$listingId/',
  path: '/products/$listingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListingIdEditRoute = ProductsListingIdEditRouteImport.update({
  id: '/products/$listingId/edit',
  path: '/products/$listingId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId/': typeof ProductsListingIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/favorites': typeof FavoritesIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId': typeof ProductsListingIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/products/$listingId/edit': typeof ProductsListingIdEditRoute
  '/products/$listingId/': typeof ProductsListingIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/favorites/'
    | '/messages/'
    | '/products/'
    | '/profile/'
    | '/products/$listingId/edit'
    | '/products/$listingId/'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/favorites'
    | '/messages'
    | '/products'
    | '/profile'
    | '/products/$listingId/edit'
    | '/products/$listingId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sell'
    | '/signup'
    | '/profile/listings'
    | '/favorites/'
    | '/messages/'
    | '/products/'
    | '/profile/'
    | '/products/$listingId/edit'
    | '/products/$listingId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  ProfileListingsRoute: typeof ProfileListingsRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProductsListingIdEditRoute: typeof ProductsListingIdEditRoute
  ProductsListingIdIndexRoute: typeof ProductsListingIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/listings': {
      id: '/profile/listings'
      path: '/profile/listings'
      fullPath: '/profile/listings'
      preLoaderRoute: typeof ProfileListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$listingId/': {
      id: '/products/$listingId/'
      path: '/products/$listingId'
      fullPath: '/products/$listingId/'
      preLoaderRoute: typeof ProductsListingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$listingId/edit': {
      id: '/products/$listingId/edit'
      path: '/products/$listingId/edit'
      fullPath: '/products/$listingId/edit'
      preLoaderRoute: typeof ProductsListingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  ProfileListingsRoute: ProfileListingsRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProductsListingIdEditRoute: ProductsListingIdEditRoute,
  ProductsListingIdIndexRoute: ProductsListingIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
